package verify

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/hdt3213/rdb/helper"
	"github.com/hdt3213/rdb/model"
)

// checkAOF verifies that every object which supports AOF conversion
// produces structurally valid RESP commands: the generated bytes must
// parse back to exactly the same command lines, command names must be
// non-empty, and expiring keys must end with a PEXPIREAT targeting the
// right key. No redis process is involved.
func checkAOF(objs []model.RedisObject) error {
	for _, obj := range objs {
		if !isDataObject(obj) {
			continue
		}
		where := fmt.Sprintf("db=%d key=%q", obj.GetDBIndex(), obj.GetKey())
		cmds := helper.ObjectToCmd(obj)
		if len(cmds) == 0 {
			return fmt.Errorf("%s: AOF conversion produced no commands", where)
		}
		for i, cmd := range cmds {
			if len(cmd) == 0 || len(cmd[0]) == 0 {
				return fmt.Errorf("%s: AOF command %d has empty command name", where, i)
			}
		}
		if obj.GetExpiration() != nil {
			last := cmds[len(cmds)-1]
			if string(last[0]) != "PEXPIREAT" {
				return fmt.Errorf("%s: expiring object should end with PEXPIREAT, got %q", where, last[0])
			}
			if len(last) != 3 || string(last[1]) != obj.GetKey() {
				return fmt.Errorf("%s: PEXPIREAT targets the wrong key", where)
			}
		}
		respBytes := helper.CmdLinesToResp(cmds)
		parsed, err := parseRESP(bytes.NewReader(respBytes))
		if err != nil {
			return fmt.Errorf("%s: generated RESP does not parse: %v", where, err)
		}
		if len(parsed) != len(cmds) {
			return fmt.Errorf("%s: RESP round-trip changed command count %d -> %d", where, len(cmds), len(parsed))
		}
		for i := range cmds {
			if len(parsed[i]) != len(cmds[i]) {
				return fmt.Errorf("%s: RESP round-trip changed arg count of command %d", where, i)
			}
			for j := range cmds[i] {
				if !bytes.Equal(parsed[i][j], cmds[i][j]) {
					return fmt.Errorf("%s: RESP round-trip changed arg %d of command %d", where, j, i)
				}
			}
		}
	}
	return nil
}

// parseRESP parses a stream of RESP2 arrays of bulk strings, the exact
// shape produced by helper.CmdLinesToResp.
func parseRESP(r io.Reader) ([][][]byte, error) {
	br := bufio.NewReader(r)
	var cmds [][][]byte
	for {
		line, err := readLine(br)
		if err == io.EOF {
			return cmds, nil
		}
		if err != nil {
			return nil, err
		}
		if len(line) == 0 || line[0] != '*' {
			return nil, fmt.Errorf("expected array header, got %q", line)
		}
		n, err := strconv.Atoi(string(line[1:]))
		if err != nil || n < 0 {
			return nil, fmt.Errorf("invalid array header %q", line)
		}
		cmd := make([][]byte, 0, n)
		for i := 0; i < n; i++ {
			header, err := readLine(br)
			if err != nil {
				return nil, err
			}
			if len(header) == 0 || header[0] != '$' {
				return nil, fmt.Errorf("expected bulk header, got %q", header)
			}
			size, err := strconv.Atoi(string(header[1:]))
			if err != nil {
				return nil, fmt.Errorf("invalid bulk header %q", header)
			}
			if size < 0 {
				cmd = append(cmd, nil)
				continue
			}
			buf := make([]byte, size+2)
			if _, err := io.ReadFull(br, buf); err != nil {
				return nil, err
			}
			if buf[size] != '\r' || buf[size+1] != '\n' {
				return nil, fmt.Errorf("bulk string not terminated by CRLF")
			}
			cmd = append(cmd, buf[:size])
		}
		cmds = append(cmds, cmd)
	}
}

func readLine(br *bufio.Reader) ([]byte, error) {
	line, err := br.ReadBytes('\n')
	if err != nil {
		if err == io.EOF && len(line) == 0 {
			return nil, io.EOF
		}
		return nil, err
	}
	if len(line) < 2 || line[len(line)-2] != '\r' {
		return nil, fmt.Errorf("line not terminated by CRLF")
	}
	return line[:len(line)-2], nil
}
