// Package verify implements the repository-level RDB fixture verification gate.
//
// It auto-discovers every *.rdb fixture under the repository and, for each one,
// performs a lossless round trip:
//
//	decode -> re-encode -> decode again -> semantic comparison
//
// Fixtures whose objects can be exported to AOF additionally get a structural
// check of the generated RESP/AOF output. Everything runs in-process without a
// Redis server, without the network and without writing into the source tree.
//
// Two kinds of "documented" outcomes are allowed:
//
//   - Negative fixtures are files that are expected to fail at an explicit stage
//     (for example an unknown opcode). They pass only when the observed failure
//     stage and message match a manifest entry.
//   - Expected losses are valid fixtures whose round trip is known to lose a
//     specific, named piece of semantics (for example LRU metadata which the
//     encoder cannot represent). They pass only when exactly the declared loss
//     reasons are observed and nothing else differs.
//
// Every other failure, as well as every missing or stale manifest entry, fails
// the gate.
package verify

import "time"

// FailureStage identifies the pipeline stage at which a negative fixture fails.
type FailureStage string

const (
	// StageDecode: the original fixture cannot be decoded.
	StageDecode FailureStage = "decode"
	// StageEncode: a decoded fixture cannot be re-encoded.
	StageEncode FailureStage = "encode"
	// StageRedeCode: the re-encoded output cannot be decoded again.
	StageRedeCode FailureStage = "redecode"
	// StageSemantic: the two decodings differ in semantics.
	StageSemantic FailureStage = "semantic"
	// StageAOF: the AOF conversion structural check fails.
	StageAOF FailureStage = "aof"
)

// LossReason is a machine-readable identifier for a known, accepted semantic loss.
type LossReason string

const (
	// LossAuxField means an AUX (global metadata) field is dropped on re-encode.
	LossAuxField LossReason = "aux-field-dropped"
	// LossEviction means LRU idle / LFU frequency metadata is dropped.
	LossEviction LossReason = "eviction-metadata-dropped"
	// LossFunctionLibrary means the serialized function library payload is dropped.
	LossFunctionLibrary LossReason = "function-library-dropped"
	// LossResizeDB means the RESIZEDB hints differ (not semantic, always accepted
	// without a declaration because they are advisory size hints).
	LossResizeDB LossReason = "resizedb-hints"
)

// ManifestEntry documents a single fixture that the gate must not treat as a
// plain success.
type ManifestEntry struct {
	// Path is the fixture path relative to the repository root.
	Path string `json:"path"`
	// Reason explains, in human terms, why this fixture is special.
	Reason string `json:"reason"`
	// ExpectedStage is the pipeline stage where a negative fixture fails.
	// Required for negative fixtures, forbidden for expected-loss entries.
	ExpectedStage FailureStage `json:"expected_stage,omitempty"`
	// ErrorContains, when non-empty, must be a substring of the observed error.
	ErrorContains string `json:"error_contains,omitempty"`
	// ExpectedLosses lists the exact loss reasons accepted for an expected-loss
	// fixture. Required for expected-loss entries, forbidden for negative ones.
	ExpectedLosses []LossReason `json:"expected_losses,omitempty"`
}

// Manifest is the on-disk negative/expected-loss fixture manifest.
type Manifest struct {
	// Entries is intentionally explicit: it must never be generated by scanning.
	Entries []ManifestEntry `json:"entries"`
}

// FixtureInfo is the collector's description of one discovered .rdb file.
type FixtureInfo struct {
	// RelPath is the repository-relative, slash-separated path.
	RelPath string
	// AbsPath is the absolute path used to open the file.
	AbsPath string
	// RDBVersion is the parsed header version (e.g. 11, 80).
	RDBVersion int
	// Flavor is "redis" or "valkey".
	Flavor string
	// Types lists every data type observed in the file (aux/string/list/...).
	Types []string
	// Encodings lists every concrete encoding observed (string/listpack/...).
	Encodings []string
	// KeyCount is the number of key-bearing objects in the file.
	KeyCount int
}

// ObjectStat records one type/encoding pair seen during collection.
type objectStat struct {
	typ      string
	encoding string
}

// SemanticLoss records one named loss observed during a round trip.
type SemanticLoss struct {
	Reason LossReason `json:"reason"`
	Detail string     `json:"detail"`
}

// SemanticDiff records one concrete semantic difference between two decodings.
type SemanticDiff struct {
	Path   string `json:"path"`
	Detail string `json:"detail"`
}

// FixtureResult is the per-fixture outcome of the verification pipeline.
type FixtureResult struct {
	Fixture FixtureInfo
	// Status is one of:
	//   "lossless"        - full round trip preserves every semantic detail
	//   "expected-loss"   - exactly the manifest-declared losses were observed
	//   "negative-ok"     - failed at the manifest-declared stage/message
	//   "failed"          - unexpected failure, undeclared loss, or manifest mismatch
	Status string `json:"status"`
	// Stage records where a negative fixture failed (when applicable).
	Stage FailureStage `json:"stage,omitempty"`
	// Error is the observed error message for failures/negative fixtures.
	Error string `json:"error,omitempty"`
	// Losses are the semantic losses observed during the round trip.
	Losses []SemanticLoss `json:"losses,omitempty"`
	// Diffs are unexpected semantic differences between the two decodings.
	Diffs []SemanticDiff `json:"diffs,omitempty"`
	// AOFStatus is "checked", "not-supported" (objects have no AOF mapping) or
	// "skipped" (negative fixtures never reach AOF conversion).
	AOFStatus string `json:"aof_status,omitempty"`
	// AOFDiff explains an AOF structural check problem, if any.
	AOFIssue string `json:"aof_issue,omitempty"`
	// Tags mark coverage of the scenarios the gate explicitly cares about,
	// e.g. "stream-v2", "hfe", "expired-key", "empty-collection".
	Tags []string `json:"tags,omitempty"`
}

// Options configures a verification run.
type Options struct {
	// RepoRoot is the repository root; all discovered paths are reported relative
	// to it. The manifest lives at <RepoRoot>/cases/verify_manifest.json.
	RepoRoot string
	// CasesDir is the directory scanned recursively for *.rdb fixtures.
	CasesDir string
	// Now is the reference "current time" used to decide whether an expiration
	// already expired. Injected so results do not depend on wall-clock drift.
	Now time.Time
}
